services:
  postgres:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gazin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/gazin
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:3001"
    depends_on:
      - backend
volumes:
  postgres_data:
